# Generated by Django 4.0.2 on 2022-04-05 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blogposts',
            new_name='Blogpost',
        ),
    ]
